# Generated by Django 4.2.30 on 2026-06-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='characterpreference',
            new_name='character_c_user_id_c8a965_idx',
            old_name='character_c_user_id_71aa5c_idx',
        ),
        migrations.RenameIndex(
            model_name='characterpreference',
            new_name='character_c_client__380a82_idx',
            old_name='character_c_client__966619_idx',
        ),
    ]
