# Generated by Django 4.2.30 on 2026-07-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('warning_code_prefixes', models.JSONField(blank=True, default=list)),
                ('warning_display_name', models.CharField(blank=True, max_length=64)),
                ('mid_land_code', models.CharField(blank=True, max_length=32)),
                ('mid_temp_code', models.CharField(blank=True, max_length=32)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': '날씨 조회 지역',
                'verbose_name_plural': '날씨 조회 지역 목록',
                'db_table': 'weather_regions',
            },
        ),
    ]
