# Generated by Django 4.2.30 on 2026-07-17 13:17

from django.db import migrations

def populate_regions(apps, schema_editor):
    WeatherRegion = apps.get_model('myweather', 'WeatherRegion')
    
    REGIONS_DATA = [
        {
            "name": "서울",
            "lat": 37.5665,
            "lon": 126.9780,
            "warning_code_prefixes": ["L110"],
            "warning_display_name": "서울",
            "mid_land_code": "11B00000",
            "mid_temp_code": "11B10101",
            "aliases": ["서울특별시"],
        },
        {
            "name": "부산",
            "lat": 35.1796,
            "lon": 129.0756,
            "warning_code_prefixes": ["L115"],
            "warning_display_name": "부산",
            "mid_land_code": "11H20000",
            "mid_temp_code": "11H20201",
            "aliases": ["부산광역시"],
        },
        {
            "name": "대구",
            "lat": 35.8714,
            "lon": 128.6014,
            "warning_code_prefixes": ["L114"],
            "warning_display_name": "대구",
            "mid_land_code": "11H10000",
            "mid_temp_code": "11H10701",
            "aliases": ["대구광역시"],
        },
        {
            "name": "인천",
            "lat": 37.4563,
            "lon": 126.7052,
            "warning_code_prefixes": ["L111"],
            "warning_display_name": "인천",
            "mid_land_code": "11B00000",
            "mid_temp_code": "11B20201",
            "aliases": ["인천광역시"],
        },
        {
            "name": "대전",
            "lat": 36.3504,
            "lon": 127.3845,
            "warning_code_prefixes": ["L112"],
            "warning_display_name": "대전",
            "mid_land_code": "11C20000",
            "mid_temp_code": "11C20401",
            "aliases": ["대전광역시"],
        },
        {
            "name": "울산",
            "lat": 35.5384,
            "lon": 129.3114,
            "warning_code_prefixes": ["L116"],
            "warning_display_name": "울산",
            "mid_land_code": "11H20000",
            "mid_temp_code": "11H20101",
            "aliases": ["울산광역시"],
        },
        {
            "name": "세종",
            "lat": 36.4800,
            "lon": 127.2890,
            "warning_code_prefixes": ["L117"],
            "warning_display_name": "세종",
            "mid_land_code": "11C20000",
            "mid_temp_code": "11C20404",
            "aliases": ["세종특별자치시"],
        },
        {
            "name": "전남광주",
            "lat": 35.1595,
            "lon": 126.8526,
            "warning_code_prefixes": ["L105", "L113"],
            "warning_display_name": "전남광주",
            "mid_land_code": "11F20000",
            "mid_temp_code": "11F20501",
            "aliases": ["전남광주통합특별시", "광주", "광주광역시", "전남", "전라남도"],
        },
        {
            "name": "경기",
            "lat": 37.2636,
            "lon": 127.0286,
            "warning_code_prefixes": ["L101"],
            "warning_display_name": "경기도",
            "mid_land_code": "11B00000",
            "mid_temp_code": "11B20601",
            "aliases": ["경기도"],
        },
        {
            "name": "강원",
            "lat": 37.8813,
            "lon": 127.7298,
            "warning_code_prefixes": ["L102"],
            "warning_display_name": "강원도",
            "mid_land_code": "11D10000",
            "mid_temp_code": "11D10301",
            "aliases": ["강원특별자치도"],
        },
        {
            "name": "충북",
            "lat": 36.6357,
            "lon": 127.4917,
            "warning_code_prefixes": ["L104"],
            "warning_display_name": "충청북도",
            "mid_land_code": "11C10000",
            "mid_temp_code": "11C10301",
            "aliases": ["충청북도"],
        },
        {
            "name": "충남",
            "lat": 36.6588,
            "lon": 126.6728,
            "warning_code_prefixes": ["L103"],
            "warning_display_name": "충청남도",
            "mid_land_code": "11C20000",
            "mid_temp_code": "11C20101",
            "aliases": ["충청남도"],
        },
        {
            "name": "전북",
            "lat": 35.8242,
            "lon": 127.1480,
            "warning_code_prefixes": ["L106"],
            "warning_display_name": "전북자치도",
            "mid_land_code": "11F10000",
            "mid_temp_code": "11F10201",
            "aliases": ["전북특별자치도", "전라북도"],
        },
        {
            "name": "경북",
            "lat": 36.5684,
            "lon": 128.7294,
            "warning_code_prefixes": ["L107", "L160"],
            "warning_display_name": "경상북도",
            "mid_land_code": "11H10000",
            "mid_temp_code": "11H10501",
            "aliases": ["경상북도", "울릉도", "독도"],
        },
        {
            "name": "경남",
            "lat": 35.2279,
            "lon": 128.6816,
            "warning_code_prefixes": ["L108"],
            "warning_display_name": "경상남도",
            "mid_land_code": "11H20000",
            "mid_temp_code": "11H20301",
            "aliases": ["경상남도"],
        },
        {
            "name": "제주",
            "lat": 33.4996,
            "lon": 126.5312,
            "warning_code_prefixes": ["L109"],
            "warning_display_name": "제주도",
            "mid_land_code": "11G00000",
            "mid_temp_code": "11G00201",
            "aliases": ["제주특별자치도"],
        },
    ]

    for data in REGIONS_DATA:
        WeatherRegion.objects.update_or_create(
            name=data["name"],
            defaults=data
        )

def rollback_regions(apps, schema_editor):
    WeatherRegion = apps.get_model('myweather', 'WeatherRegion')
    WeatherRegion.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('myweather', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_regions, rollback_regions),
    ]
