# Generated by Django 4.2.30 on 2026-07-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweather', '0002_populate_weather_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherPhrasingFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_word', models.CharField(max_length=64, unique=True, verbose_name='기본 단어')),
                ('target_word', models.CharField(max_length=64, verbose_name='순화 단어')),
                ('condition_trigger', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='기상 조건 트리거(맑음 등)')),
            ],
            options={
                'verbose_name': '날씨 순화 필터',
                'verbose_name_plural': '날씨 순화 필터 목록',
                'db_table': 'weather_phrasing_filters',
            },
        ),
    ]
