# Generated by Django 4.2.30 on 2026-07-17 13:27

from django.db import migrations

def populate_phrasing_filters(apps, schema_editor):
    WeatherPhrasingFilter = apps.get_model('myweather', 'WeatherPhrasingFilter')
    
    FILTERS_DATA = [
        # Normal replacements (no condition trigger)
        {"source_word": "혈액 순환", "target_word": "기분 전환", "condition_trigger": None},
        {"source_word": "면역", "target_word": "컨디션", "condition_trigger": None},
        {"source_word": "치료", "target_word": "돌봄", "condition_trigger": None},
        {"source_word": "증상", "target_word": "몸의 신호", "condition_trigger": None},
        {"source_word": "완화", "target_word": "덜어내기", "condition_trigger": None},
        {"source_word": "분위기이", "target_word": "분위기가", "condition_trigger": None},
        {"source_word": "창문 밖은 비 소식은", "target_word": "창문 밖은 비 소식이", "condition_trigger": None},
        {"source_word": "밖은 비 소식은", "target_word": "밖은 비 소식이", "condition_trigger": None},
        {"source_word": "비 소식은 적고", "target_word": "비 소식이 적고", "condition_trigger": None},
        
        # Condition-specific replacements (trigger: "맑음")
        {"source_word": "따뜻한 햇살", "target_word": "밝은 바깥 분위기", "condition_trigger": "맑음"},
        {"source_word": "강한 햇살", "target_word": "밝은 바깥 분위기", "condition_trigger": "맑음"},
        {"source_word": "햇살", "target_word": "바깥 분위기", "condition_trigger": "맑음"},
        {"source_word": "햇빛", "target_word": "바깥 공기", "condition_trigger": "맑음"},
        {"source_word": "신선한 공기와 ", "target_word": "바깥 공기가 ", "condition_trigger": "맑음"},
        {"source_word": "맑은 공기", "target_word": "가벼운 바깥 공기", "condition_trigger": "맑음"},
        {"source_word": "맑고", "target_word": "비 소식은 적고", "condition_trigger": "맑음"},
        {"source_word": "맑은", "target_word": "비 소식이 적은", "condition_trigger": "맑음"},
        {"source_word": "자외선 차단제를 바르는", "target_word": "외출 전 바깥 상황을 한 번 확인하는", "condition_trigger": "맑음"},
        {"source_word": "자외선 차단제", "target_word": "외출 준비", "condition_trigger": "맑음"},
    ]

    for data in FILTERS_DATA:
        WeatherPhrasingFilter.objects.update_or_create(
            source_word=data["source_word"],
            defaults=data
        )

def rollback_phrasing_filters(apps, schema_editor):
    WeatherPhrasingFilter = apps.get_model('myweather', 'WeatherPhrasingFilter')
    WeatherPhrasingFilter.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('myweather', '0003_weatherphrasingfilter'),
    ]

    operations = [
        migrations.RunPython(populate_phrasing_filters, rollback_phrasing_filters),
    ]
