# Generated by Django 4.2.30 on 2026-07-02 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('conversation_id', models.BigIntegerField(db_index=True)),
                ('role', models.CharField(db_index=True, max_length=20)),
                ('message_text', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'conversation_logs',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceKeywordSummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('period_type', models.CharField(db_index=True, max_length=20)),
                ('period_key', models.CharField(db_index=True, max_length=20)),
                ('reflected_conversation_count', models.IntegerField(default=0)),
                ('reflected_message_count', models.IntegerField(default=0)),
                ('display_threshold', models.IntegerField(default=5)),
                ('keywords_json', models.TextField(blank=True, default='[]')),
                ('analyzed_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'preference_keyword_summaries',
                'ordering': ['-analyzed_at', '-id'],
                'indexes': [models.Index(fields=['user_id', 'period_type', 'period_key'], name='preference__user_id_c62602_idx'), models.Index(fields=['user_id', 'analyzed_at'], name='preference__user_id_b3bba9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PreferenceEvidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('period_key', models.CharField(db_index=True, max_length=20)),
                ('normalized_keyword', models.CharField(db_index=True, max_length=100)),
                ('preference_type', models.CharField(db_index=True, max_length=50)),
                ('evidence_text', models.TextField()),
                ('conversation_context', models.TextField()),
                ('source_created_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='preference_evidence', to='taste.conversationlog')),
            ],
            options={
                'db_table': 'preference_evidence',
                'ordering': ['-source_created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationlog',
            index=models.Index(fields=['user_id', 'role', 'created_at'], name='conversatio_user_id_a3232d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationlog',
            index=models.Index(fields=['conversation_id', 'created_at'], name='conversatio_convers_e50dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenceevidence',
            index=models.Index(fields=['user_id', 'period_key', 'normalized_keyword'], name='preference__user_id_8c29eb_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenceevidence',
            index=models.Index(fields=['user_id', 'preference_type', 'period_key'], name='preference__user_id_1e66dd_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenceevidence',
            index=models.Index(fields=['message'], name='preference__message_a2fcf0_idx'),
        ),
    ]
