# Generated by Django 4.2.30 on 2026-07-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taste', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversationlog',
            new_name='conversatio_user_id_a3232d_idx',
            old_name='taste_conv_user_role_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationlog',
            new_name='conversatio_convers_e50dbf_idx',
            old_name='taste_conv_conv_idx',
        ),
        migrations.RenameIndex(
            model_name='preferenceevidence',
            new_name='preference__user_id_8c29eb_idx',
            old_name='taste_pref_ev_user_period_idx',
        ),
        migrations.RenameIndex(
            model_name='preferenceevidence',
            new_name='preference__user_id_1e66dd_idx',
            old_name='taste_pref_ev_user_type_idx',
        ),
        migrations.RenameIndex(
            model_name='preferenceevidence',
            new_name='preference__message_a2fcf0_idx',
            old_name='taste_pref_ev_msg_idx',
        ),
        migrations.RenameIndex(
            model_name='preferencekeywordsummary',
            new_name='preference__user_id_c62602_idx',
            old_name='taste_pref_kw_user_period_idx',
        ),
        migrations.RenameIndex(
            model_name='preferencekeywordsummary',
            new_name='preference__user_id_b3bba9_idx',
            old_name='taste_pref_kw_user_analyzed_idx',
        ),
    ]
