# Generated by Django 4.2.30 on 2026-07-14 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.CharField(max_length=48)),
                ('code', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=160)),
                ('visual_prompt', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionCardAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_input', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('analysis_status', models.CharField(default='CLEAR', max_length=32)),
                ('safety_status', models.CharField(default='SAFE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionCardJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('style_id', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionCardScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scene_hash', models.CharField(db_index=True, max_length=64)),
                ('scene_spec', models.JSONField(default=dict)),
                ('available_styles', models.JSONField(default=list)),
                ('safety_status', models.CharField(default='SAFE', max_length=16)),
                ('invalidated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedEmotionCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('style_id', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, default='')),
                ('image_alt', models.CharField(max_length=240)),
                ('summary', models.CharField(max_length=240)),
                ('feedback', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialCompanionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=24, unique=True)),
                ('social_context', models.CharField(db_index=True, max_length=40)),
                ('companion_type', models.CharField(max_length=64)),
                ('companion_count_max', models.PositiveSmallIntegerField(default=0)),
                ('visual_prompt', models.TextField()),
                ('privacy_note', models.CharField(blank=True, max_length=240)),
                ('weight', models.IntegerField(default=35)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=48)),
                ('rule_id', models.CharField(max_length=80)),
                ('data', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['rule_type', 'enabled'], name='emotion_car_rule_ty_099206_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ruleentry',
            constraint=models.UniqueConstraint(fields=('rule_type', 'rule_id'), name='emotion_rule_entry_unique'),
        ),
        migrations.AddField(
            model_name='generatedemotioncard',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='emotion_cards.emotioncardscene'),
        ),
        migrations.AddField(
            model_name='generatedemotioncard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='featurecode',
            index=models.Index(fields=['group', 'code'], name='emotion_car_group_c4124e_idx'),
        ),
        migrations.AddConstraint(
            model_name='featurecode',
            constraint=models.UniqueConstraint(fields=('group', 'code'), name='emotion_feature_code_unique'),
        ),
        migrations.AddField(
            model_name='emotioncardscene',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='emotion_cards.emotioncardanalysis'),
        ),
        migrations.AddField(
            model_name='emotioncardscene',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_card_scenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emotioncardjob',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='emotion_cards.generatedemotioncard'),
        ),
        migrations.AddField(
            model_name='emotioncardjob',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='emotion_cards.emotioncardscene'),
        ),
        migrations.AddField(
            model_name='emotioncardjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_card_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emotioncardanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_card_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='catalogentry',
            index=models.Index(fields=['catalog', 'code', 'enabled'], name='emotion_car_catalog_98d19e_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogentry',
            constraint=models.UniqueConstraint(fields=('catalog', 'code'), name='emotion_catalog_entry_unique'),
        ),
        migrations.AddIndex(
            model_name='generatedemotioncard',
            index=models.Index(fields=['user', 'created_at'], name='emotion_car_user_id_d1a169_idx'),
        ),
        migrations.AddIndex(
            model_name='emotioncardscene',
            index=models.Index(fields=['user', 'scene_hash'], name='emotion_car_user_id_45ff05_idx'),
        ),
        migrations.AddIndex(
            model_name='emotioncardjob',
            index=models.Index(fields=['user', 'created_at'], name='emotion_car_user_id_1e38e4_idx'),
        ),
        migrations.AddIndex(
            model_name='emotioncardanalysis',
            index=models.Index(fields=['user', 'created_at'], name='emotion_car_user_id_69b1b2_idx'),
        ),
    ]
