# Generated by Django 4.2.30 on 2026-07-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionCardUsageReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_card_usage_reset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
