# Generated by Django 4.2.30 on 2026-06-30 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MbtiEvidenceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_store_key', models.CharField(max_length=255)),
                ('embedding_model', models.CharField(max_length=64)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mbti_evidence_embeddings',
                'ordering': ['-embedded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MbtiMonthlyAnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('period_key', models.CharField(db_index=True, max_length=7)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('complete', 'complete'), ('skipped', 'skipped'), ('failed', 'failed')], db_index=True, default='pending', max_length=32)),
                ('trigger_source', models.CharField(choices=[('monthly_scheduler', 'monthly_scheduler'), ('dashboard_on_demand', 'dashboard_on_demand'), ('manual', 'manual')], default='monthly_scheduler', max_length=32)),
                ('input_hash', models.CharField(db_index=True, max_length=128)),
                ('scoring_model', models.CharField(blank=True, max_length=64, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=64, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mbti_monthly_analysis_jobs',
                'ordering': ['scheduled_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MbtiMonthlyAxisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('period_key', models.CharField(db_index=True, max_length=7)),
                ('axis', models.CharField(choices=[('IE', 'IE'), ('SN', 'SN'), ('TF', 'TF'), ('JP', 'JP')], db_index=True, max_length=2)),
                ('qna_count', models.IntegerField(default=0)),
                ('required_qna_count', models.IntegerField(default=5)),
                ('primary_open', models.BooleanField(default=False)),
                ('scored_count', models.IntegerField(default=0)),
                ('required_scored_count', models.IntegerField(default=1)),
                ('secondary_open', models.BooleanField(default=False)),
                ('axis_avg', models.FloatField(blank=True, null=True)),
                ('axis_ratios_json', models.JSONField(blank=True, default=dict)),
                ('selected_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('data_status', models.CharField(choices=[('current_month', 'current_month'), ('primary_closed', 'primary_closed'), ('secondary_closed', 'secondary_closed'), ('tie_carried', 'tie_carried'), ('carried_from_previous', 'carried_from_previous'), ('carried_from_onboarding', 'carried_from_onboarding'), ('insufficient_axis_data', 'insufficient_axis_data')], db_index=True, max_length=32)),
                ('calculation_status', models.CharField(blank=True, max_length=32, null=True)),
                ('baseline_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('baseline_source', models.CharField(blank=True, choices=[('latest_monthly_result', 'latest_monthly_result'), ('onboarding', 'onboarding'), ('none', 'none')], max_length=32, null=True)),
                ('baseline_period_key', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mbti_monthly_axis_results',
                'ordering': ['monthly_result_id', 'axis'],
            },
        ),
        migrations.CreateModel(
            name='MbtiMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_sections_json', models.JSONField(blank=True, default=list)),
                ('evidence_items_json', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mbti_monthly_reports',
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MbtiMonthlyResultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('period_key', models.CharField(db_index=True, max_length=7)),
                ('previous_estimated_mbti_type', models.CharField(blank=True, max_length=4, null=True)),
                ('previous_period_key', models.CharField(blank=True, max_length=7, null=True)),
                ('estimated_mbti_type', models.CharField(blank=True, max_length=4, null=True)),
                ('changed_axes_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='complete', max_length=32)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mbti_monthly_results',
                'ordering': ['-period_key', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MbtiOnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('mbti_type', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mbti_onboarding_profiles',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MbtiQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('conversation_id', models.BigIntegerField(blank=True, null=True)),
                ('question_message_id', models.BigIntegerField(blank=True, null=True)),
                ('answer_message_id', models.BigIntegerField(blank=True, null=True)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('target_axis', models.CharField(choices=[('IE', 'IE'), ('SN', 'SN'), ('TF', 'TF'), ('JP', 'JP')], max_length=2)),
                ('period_key', models.CharField(db_index=True, max_length=7)),
                ('answered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mbti_question_responses',
                'ordering': ['answered_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MbtiResponseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('period_key', models.CharField(db_index=True, max_length=7)),
                ('axis', models.CharField(choices=[('IE', 'IE'), ('SN', 'SN'), ('TF', 'TF'), ('JP', 'JP')], db_index=True, max_length=2)),
                ('score', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(default='unknown', max_length=16)),
                ('coding_status', models.CharField(choices=[('coded', 'coded'), ('insufficient_context', 'insufficient_context'), ('failed', 'failed')], db_index=True, max_length=32)),
                ('evidence_span', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=64, null=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('question_response', models.OneToOneField(db_column='question_response_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='score_result', to='mbti.mbtiquestionresponse')),
            ],
            options={
                'db_table': 'mbti_response_scores',
                'ordering': ['question_response_id'],
            },
        ),
        migrations.AddIndex(
            model_name='mbtiquestionresponse',
            index=models.Index(fields=['user_id', 'period_key', 'target_axis'], name='mbti_questi_user_id_f8328f_idx'),
        ),
        migrations.AddIndex(
            model_name='mbtiquestionresponse',
            index=models.Index(fields=['user_id', 'answered_at'], name='mbti_questi_user_id_615d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='mbtionboardingprofile',
            index=models.Index(fields=['user_id'], name='mbti_onboar_user_id_a88f34_idx'),
        ),
        migrations.AddIndex(
            model_name='mbtimonthlyresultrecord',
            index=models.Index(fields=['user_id', 'period_key'], name='mbti_monthl_user_id_e53655_idx'),
        ),
        migrations.AddIndex(
            model_name='mbtimonthlyresultrecord',
            index=models.Index(fields=['user_id', 'status', 'period_key'], name='mbti_monthl_user_id_adf9af_idx'),
        ),
        migrations.AddConstraint(
            model_name='mbtimonthlyresultrecord',
            constraint=models.UniqueConstraint(fields=('user_id', 'period_key'), name='uniq_mbti_monthly_result_user_period'),
        ),
        migrations.AddField(
            model_name='mbtimonthlyreport',
            name='monthly_result',
            field=models.OneToOneField(db_column='monthly_result_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to='mbti.mbtimonthlyresultrecord'),
        ),
        migrations.AddField(
            model_name='mbtimonthlyaxisresult',
            name='monthly_result',
            field=models.ForeignKey(db_column='monthly_result_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='axis_results', to='mbti.mbtimonthlyresultrecord'),
        ),
        migrations.AddField(
            model_name='mbtimonthlyanalysisjob',
            name='monthly_result',
            field=models.OneToOneField(blank=True, db_column='monthly_result_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysis_job', to='mbti.mbtimonthlyresultrecord'),
        ),
        migrations.AddField(
            model_name='mbtievidenceembedding',
            name='response_score',
            field=models.OneToOneField(db_column='response_score_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='evidence_embedding', to='mbti.mbtiresponsescore'),
        ),
        migrations.AddIndex(
            model_name='mbtiresponsescore',
            index=models.Index(fields=['user_id', 'period_key', 'axis'], name='mbti_respon_user_id_7f81e9_idx'),
        ),
        migrations.AddIndex(
            model_name='mbtiresponsescore',
            index=models.Index(fields=['axis', 'coding_status'], name='mbti_respon_axis_b25e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='mbtiresponsescore',
            index=models.Index(fields=['question_response'], name='mbti_respon_questio_9b4a85_idx'),
        ),
        migrations.AddIndex(
            model_name='mbtimonthlyreport',
            index=models.Index(fields=['monthly_result'], name='mbti_monthl_monthly_89d2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='mbtimonthlyaxisresult',
            index=models.Index(fields=['monthly_result', 'axis'], name='mbti_monthl_monthly_bc7a24_idx'),
        ),
        migrations.AddIndex(
            model_name='mbtimonthlyaxisresult',
            index=models.Index(fields=['user_id', 'period_key', 'axis'], name='mbti_monthl_user_id_3ee6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='mbtimonthlyaxisresult',
            index=models.Index(fields=['user_id', 'axis', 'period_key'], name='mbti_monthl_user_id_e8ea97_idx'),
        ),
        migrations.AddConstraint(
            model_name='mbtimonthlyaxisresult',
            constraint=models.UniqueConstraint(fields=('monthly_result', 'axis'), name='uniq_mbti_monthly_axis_result'),
        ),
        migrations.AddIndex(
            model_name='mbtimonthlyanalysisjob',
            index=models.Index(fields=['status', 'scheduled_at'], name='mbti_monthl_status_b38b69_idx'),
        ),
        migrations.AddIndex(
            model_name='mbtimonthlyanalysisjob',
            index=models.Index(fields=['user_id', 'period_key'], name='mbti_monthl_user_id_63b490_idx'),
        ),
        migrations.AddIndex(
            model_name='mbtimonthlyanalysisjob',
            index=models.Index(fields=['user_id', 'period_key', 'input_hash'], name='mbti_monthl_user_id_338e9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='mbtimonthlyanalysisjob',
            constraint=models.UniqueConstraint(fields=('user_id', 'period_key', 'input_hash', 'prompt_version'), name='uniq_mbti_analysis_job_input_prompt'),
        ),
        migrations.AddIndex(
            model_name='mbtievidenceembedding',
            index=models.Index(fields=['response_score'], name='mbti_eviden_respons_83f33e_idx'),
        ),
        migrations.AddIndex(
            model_name='mbtievidenceembedding',
            index=models.Index(fields=['vector_store_key'], name='mbti_eviden_vector__0c339b_idx'),
        ),
    ]
