# Generated by Django 6.0.6 on 2026-06-22 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalScale',
            fields=[
                ('scale_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('scale_name_ko', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=50)),
                ('time_frame', models.CharField(blank=True, max_length=100)),
                ('estimated_minutes', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'clinical_scales',
            },
        ),
        migrations.CreateModel(
            name='ScaleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_value', models.IntegerField()),
                ('option_label', models.CharField(max_length=100)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='wellness.clinicalscale')),
            ],
            options={
                'db_table': 'scale_options',
            },
        ),
        migrations.CreateModel(
            name='ScaleQuestion',
            fields=[
                ('question_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('question_number', models.IntegerField()),
                ('text', models.TextField()),
                ('is_reverse', models.BooleanField(default=False)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='wellness.clinicalscale')),
            ],
            options={
                'db_table': 'scale_questions',
            },
        ),
        migrations.CreateModel(
            name='UserScaleEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_date', models.DateField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.clinicalscale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_scale_estimates',
                'ordering': ['-target_date'],
            },
        ),
    ]
