# Generated by Django 4.2.30 on 2026-06-30 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_user_mypage_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMypageProfile',
        ),
    ]
