# Generated by Django 4.2.30 on 2026-07-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='character',
            field=models.CharField(blank=True, choices=[('pori', '포리'), ('kkami', '까미'), ('toto', '토토'), ('yeoul', '여울')], max_length=10),
        ),
    ]
