import csv

from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone

from emotion_cards.models import (
    CatalogEntry,
    FeatureCode,
    RuleEntry,
    SocialCompanionRule,
)

from .import_emotion_card_data import (
    DATA_DIR,
    _headers,
    _rows,
    validate_data_files,
)


REPORT_FIELDS = ["check", "status", "value", "detail"]


def _write_csv(path, fields, rows):
    with path.open("w", encoding="utf-8-sig", newline="") as target:
        writer = csv.DictWriter(target, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def _update_manifest_for_report():
    path = DATA_DIR / "00_manifest.csv"
    fields = _headers(path)
    rows = _rows(path)
    report_path = DATA_DIR / "26_validation_report.csv"
    report_row = next(
        row for row in rows if row.get("file_name") == report_path.name
    )
    report_row["row_count"] = str(len(_rows(report_path)))
    report_row["column_count"] = str(len(_headers(report_path)))
    _write_csv(path, fields, rows)


def regenerate_validation_report(report):
    rows = [
        {
            "check": name,
            "status": "PASS",
            "value": value,
            "detail": detail,
        }
        for name, value, detail in report["checks"]
    ]
    rows.extend(
        {
            "check": "warning",
            "status": "WARN",
            "value": "",
            "detail": warning,
        }
        for warning in report["warnings"]
    )
    rows.extend(
        {
            "check": "error",
            "status": "FAIL",
            "value": "",
            "detail": error,
        }
        for error in report["errors"]
    )
    rows.append({
        "check": "generated_at",
        "status": "PASS" if not report["errors"] else "FAIL",
        "value": timezone.now().isoformat(),
        "detail": "generated by validate_emotion_card_data",
    })
    _write_csv(
        DATA_DIR / "26_validation_report.csv",
        REPORT_FIELDS,
        rows,
    )
    _update_manifest_for_report()


class Command(BaseCommand):
    help = "Validate emotion-card v2 CSV integrity and regenerate report 26."

    def add_arguments(self, parser):
        parser.add_argument("--strict", action="store_true")

    def handle(self, *args, **options):
        report = validate_data_files()
        regenerate_validation_report(report)

        # The generated report changes its own row count, so validate once more
        # after synchronizing that count in the manifest.
        report = validate_data_files()
        failures = list(report["errors"])
        if options["strict"]:
            failures.extend(report["warnings"])
        if failures:
            raise CommandError("; ".join(failures))

        required_seed = (
            (FeatureCode, "feature codes"),
            (CatalogEntry, "catalog entries"),
            (RuleEntry, "rules"),
            (SocialCompanionRule, "social companion rules"),
        )
        missing = [
            label
            for model, label in required_seed
            if not model.objects.exists()
        ]
        if missing:
            raise CommandError(
                "Database seed is empty for "
                + ", ".join(missing)
                + "; run import_emotion_card_data first."
            )
        required_rule_types = {
            "conflict_priority",
            "prompt_template",
            "output_schema",
            "extraction_example",
            "scene_mapping_test",
        }
        actual_rule_types = set(
            RuleEntry.objects.filter(
                rule_type__in=required_rule_types,
                enabled=True,
            ).values_list("rule_type", flat=True)
        )
        if actual_rule_types != required_rule_types:
            raise CommandError(
                "Runtime rule seed missing: "
                + ", ".join(sorted(required_rule_types - actual_rule_types))
            )

        for warning in report["warnings"]:
            self.stdout.write(self.style.WARNING(f"Warning: {warning}"))
        self.stdout.write(
            self.style.SUCCESS(
                "Emotion-card v2 CSV and database seed validation passed."
            )
        )
