# Generated by Django 4.2.30 on 2026-06-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyfortune',
            new_name='calendar_ap_user_id_aff7dc_idx',
            old_name='calendar_ap_user_id_6d2f43_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyfortune',
            new_name='calendar_ap_client__8a60b4_idx',
            old_name='calendar_ap_client__e126ba_idx',
        ),
    ]
