# Generated by Django 4.2.30 on 2026-07-13 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('helpfulness', models.PositiveSmallIntegerField()),
                ('feedback_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'checkin_action_feedback',
            },
        ),
        migrations.CreateModel(
            name='CauseOption',
            fields=[
                ('cause_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cause_code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=180)),
                ('hint', models.CharField(blank=True, max_length=240)),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('chat_seed', models.CharField(blank=True, max_length=240)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'checkin_cause_options',
                'ordering': ['display_order', 'cause_id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.CharField(max_length=20)),
                ('stage', models.CharField(max_length=30)),
                ('fragment_key', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'checkin_character_fragments',
            },
        ),
        migrations.CreateModel(
            name='CharacterToneRule',
            fields=[
                ('character_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tone', models.CharField(max_length=120)),
                ('avoid_phrases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'checkin_character_tone_rules',
            },
        ),
        migrations.CreateModel(
            name='CheckinRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'checkin_recommendations',
                'ordering': ['rank', 'action_id'],
            },
        ),
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('stage', models.CharField(choices=[('REFLECTION', 'REFLECTION'), ('CAUSE', 'CAUSE'), ('NEED', 'NEED'), ('RECOMMENDATION', 'RECOMMENDATION'), ('FINAL_ROUTE', 'FINAL_ROUTE'), ('COMPLETED', 'COMPLETED')], default='REFLECTION', max_length=30)),
                ('primary_emotion', models.CharField(blank=True, choices=[('JOY', 'JOY'), ('SADNESS', 'SADNESS'), ('ANGER', 'ANGER'), ('ANXIETY', 'ANXIETY')], max_length=20)),
                ('secondary_emotion', models.CharField(blank=True, choices=[('JOY', 'JOY'), ('SADNESS', 'SADNESS'), ('ANGER', 'ANGER'), ('ANXIETY', 'ANXIETY')], max_length=20)),
                ('state_tags', models.JSONField(blank=True, default=list)),
                ('energy_level', models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=10)),
                ('final_route', models.CharField(blank=True, choices=[('CHAT', 'CHAT'), ('ACTION', 'ACTION'), ('RECORD_ONLY', 'RECORD_ONLY')], max_length=20)),
                ('character_id', models.CharField(blank=True, max_length=20)),
                ('character_snapshot', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'checkin_daily_checkins',
            },
        ),
        migrations.CreateModel(
            name='DialogueTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=30)),
                ('context_key', models.CharField(default='base', max_length=50)),
                ('template', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'checkin_dialogue_templates',
            },
        ),
        migrations.CreateModel(
            name='NeedOption',
            fields=[
                ('need_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=180)),
                ('hint', models.CharField(blank=True, max_length=240)),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('response_mode', models.CharField(default='GENTLE', max_length=50)),
                ('llm_instruction', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'checkin_need_options',
                'ordering': ['display_order', 'need_id'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(max_length=100)),
                ('target_action_ids', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'checkin_preference_mappings',
            },
        ),
        migrations.CreateModel(
            name='RecommendationAction',
            fields=[
                ('action_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('expected_minutes', models.PositiveIntegerField(default=3)),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('suitable_needs', models.JSONField(blank=True, default=list)),
                ('suitable_emotions', models.JSONField(blank=True, default=list)),
                ('energy_levels', models.JSONField(blank=True, default=list)),
                ('linked_keywords', models.JSONField(blank=True, default=list)),
                ('avoid_emotions', models.JSONField(blank=True, default=list)),
                ('avoid_causes', models.JSONField(blank=True, default=list)),
                ('default_weight', models.IntegerField(default=0)),
                ('safety_notice', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'checkin_recommendation_actions',
                'ordering': ['-default_weight', 'action_id'],
            },
        ),
        migrations.CreateModel(
            name='ReflectionOption',
            fields=[
                ('reflection_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=180)),
                ('hint', models.CharField(blank=True, max_length=240)),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('primary_emotion', models.CharField(choices=[('JOY', 'JOY'), ('SADNESS', 'SADNESS'), ('ANGER', 'ANGER'), ('ANXIETY', 'ANXIETY')], max_length=20)),
                ('state_tags', models.JSONField(blank=True, default=list)),
                ('energy_level', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='MEDIUM', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'checkin_reflection_options',
                'ordering': ['display_order', 'reflection_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='preferencemapping',
            constraint=models.UniqueConstraint(fields=('source_label',), name='uniq_checkin_preference_source'),
        ),
        migrations.AddConstraint(
            model_name='dialoguetemplate',
            constraint=models.UniqueConstraint(fields=('stage', 'context_key'), name='uniq_checkin_dialogue_template'),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='checkin.causeoption'),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='checkin.needoption'),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='reflection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='checkin.reflectionoption'),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='selected_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selected_checkins', to='checkin.recommendationaction'),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkinrecommendation',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='checkin.recommendationaction'),
        ),
        migrations.AddField(
            model_name='checkinrecommendation',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='checkin.dailycheckin'),
        ),
        migrations.AddConstraint(
            model_name='characterfragment',
            constraint=models.UniqueConstraint(fields=('character_id', 'stage', 'fragment_key'), name='uniq_checkin_character_fragment'),
        ),
        migrations.AddField(
            model_name='actionfeedback',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='checkin.recommendationaction'),
        ),
        migrations.AddField(
            model_name='actionfeedback',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='checkin.dailycheckin'),
        ),
        migrations.AddIndex(
            model_name='dailycheckin',
            index=models.Index(fields=['user', 'checkin_date'], name='checkin_dai_user_id_5bd0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='dailycheckin',
            index=models.Index(fields=['user', 'stage'], name='checkin_dai_user_id_b1911b_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailycheckin',
            constraint=models.UniqueConstraint(fields=('user', 'checkin_date'), name='uniq_checkin_user_date'),
        ),
        migrations.AddConstraint(
            model_name='checkinrecommendation',
            constraint=models.UniqueConstraint(fields=('checkin', 'action'), name='uniq_checkin_recommendation_action'),
        ),
        migrations.AddConstraint(
            model_name='actionfeedback',
            constraint=models.UniqueConstraint(fields=('checkin', 'action'), name='uniq_checkin_action_feedback'),
        ),
    ]
