# Generated by Django 4.2.30 on 2026-07-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseContextConfig',
            fields=[
                ('cause_context', models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('DIFFICULT', 'DIFFICULT'), ('MIXED', 'MIXED'), ('NEUTRAL', 'NEUTRAL'), ('SKIP', 'SKIP')], max_length=20, primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('question_text', models.CharField(max_length=240)),
                ('option_text_field', models.CharField(blank=True, max_length=50)),
                ('show_cause_options', models.BooleanField(default=True)),
                ('next_stage', models.CharField(default='CAUSE', max_length=30)),
                ('weekly_label', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'db_table': 'checkin_cause_contexts',
                'ordering': ['display_order', 'cause_context'],
            },
        ),
        migrations.AddField(
            model_name='causeoption',
            name='available_contexts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='causeoption',
            name='chat_seed_templates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='causeoption',
            name='examples_internal',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='causeoption',
            name='option_text_difficult',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='causeoption',
            name='option_text_mixed',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='causeoption',
            name='option_text_neutral',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='causeoption',
            name='option_text_positive',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='causeoption',
            name='sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='cause_context',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'POSITIVE'), ('DIFFICULT', 'DIFFICULT'), ('MIXED', 'MIXED'), ('NEUTRAL', 'NEUTRAL'), ('SKIP', 'SKIP')], max_length=20),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='cause_display_text_snapshot',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='needoption',
            name='need_code',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reflectionoption',
            name='ack_key',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='reflectionoption',
            name='cause_context',
            field=models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('DIFFICULT', 'DIFFICULT'), ('MIXED', 'MIXED'), ('NEUTRAL', 'NEUTRAL'), ('SKIP', 'SKIP')], default='DIFFICULT', max_length=20),
        ),
        migrations.AddField(
            model_name='reflectionoption',
            name='emotion_intensity_default',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reflectionoption',
            name='include_weekly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reflectionoption',
            name='next_stage',
            field=models.CharField(default='CAUSE', max_length=30),
        ),
        migrations.AddField(
            model_name='reflectionoption',
            name='secondary_emotion',
            field=models.CharField(blank=True, choices=[('JOY', 'JOY'), ('SADNESS', 'SADNESS'), ('ANGER', 'ANGER'), ('ANXIETY', 'ANXIETY')], max_length=20),
        ),
    ]
