# Generated by Django 4.2.30 on 2026-07-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_causecontextconfig_causeoption_available_contexts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('UNKNOWN', 'UNKNOWN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reflectionoption',
            name='energy_level',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('UNKNOWN', 'UNKNOWN')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='reflectionoption',
            name='primary_emotion',
            field=models.CharField(blank=True, choices=[('JOY', 'JOY'), ('SADNESS', 'SADNESS'), ('ANGER', 'ANGER'), ('ANXIETY', 'ANXIETY')], max_length=20),
        ),
    ]
