# Generated by Django 6.0.6 on 2026-06-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_tea_bgm_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('anger', '분노'), ('sadness', '슬픔'), ('anxiety', '불안'), ('hurt', '상처'), ('fluster', '당황'), ('joy', '기쁨')], max_length=10, verbose_name='감정 코드')),
                ('quote', models.TextField(verbose_name='에세이/도서 구절')),
                ('book_title', models.CharField(max_length=150, verbose_name='도서명')),
                ('author', models.CharField(max_length=100, verbose_name='저자')),
            ],
            options={
                'verbose_name': '도서 큐레이션',
                'verbose_name_plural': '도서 큐레이션 목록',
                'db_table': 'book_curations',
            },
        ),
        migrations.CreateModel(
            name='WalkCuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('anger', '분노'), ('sadness', '슬픔'), ('anxiety', '불안'), ('hurt', '상처'), ('fluster', '당황'), ('joy', '기쁨')], max_length=10, verbose_name='감정 코드')),
                ('name', models.CharField(max_length=100, verbose_name='산책로/활동 명칭')),
                ('duration', models.CharField(max_length=50, verbose_name='소요 시간')),
                ('description', models.TextField(verbose_name='활동 및 추천 코스 설명')),
            ],
            options={
                'verbose_name': '산책 큐레이션',
                'verbose_name_plural': '산책 큐레이션 목록',
                'db_table': 'walk_curations',
            },
        ),
        migrations.AlterField(
            model_name='bgmrecommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tearecommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
