# Generated by Django 6.0.6 on 2026-06-28 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_emotion4'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlopsQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_score', models.SmallIntegerField(verbose_name='피드백 점수 (1=좋아요, -1=싫어요)')),
                ('status', models.CharField(choices=[('pending', '재학습 대기 중'), ('processed', '재학습 반영 완료')], default='pending', max_length=20, verbose_name='재학습 반영 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='피드백 수신 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='상태 변경 일시')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlops_feedbacks', to='chat.chatmessage', verbose_name='대상 메시지')),
            ],
            options={
                'verbose_name': 'MLOps 피드백 대기열',
                'verbose_name_plural': 'MLOps 피드백 대기열 목록',
                'db_table': 'mlops_queue',
                'ordering': ['-created_at'],
            },
        ),
    ]
