# Generated by Django 4.2.30 on 2026-07-02 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_character'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_mlopsqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='memory', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('summary_text', models.TextField(blank=True, default='', verbose_name='장기 요약')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '장기 요약 메모리',
                'verbose_name_plural': '장기 요약 메모리 목록',
                'db_table': 'user_memory',
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='cold_start_done',
            field=models.BooleanField(default=False, verbose_name='감정 선택 질문 답변 완료'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='mbti_candidate_answer',
            field=models.TextField(blank=True, null=True, verbose_name='시크릿 모드에서 저장 동의 대기 중인 MBTI 답변'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='mbti_last_question_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='mbti_pending',
            field=models.BooleanField(default=False, verbose_name='MBTI 질문 pending 플래그'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='selected_emotion',
            field=models.CharField(blank=True, choices=[('joy', '기쁨'), ('sadness', '슬픔'), ('anger', '분노'), ('normal', '일반')], max_length=10, null=True, verbose_name='콜드스타트에서 선택한 초기 감정'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='character',
            field=models.CharField(choices=[('pori', '포리'), ('kkami', '까미'), ('toto', '토토'), ('yeoul', '여울')], default='pori', max_length=10),
        ),
        migrations.CreateModel(
            name='MbtiAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_code', models.CharField(max_length=20, verbose_name='MBTI 유도 질문 코드')),
                ('answer_text', models.TextField(verbose_name='사용자 답변 원문')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mbti_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MBTI 답변',
                'verbose_name_plural': 'MBTI 답변 목록',
                'db_table': 'mbti_answers',
                'ordering': ['-created_at'],
            },
        ),
    ]
