# Generated by Django 4.2.30 on 2026-07-19 15:07

import chat.crypto_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_delete_walkcuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=chat.crypto_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='usermemory',
            name='summary_text',
            field=chat.crypto_fields.EncryptedTextField(blank=True, default='', verbose_name='장기 요약'),
        ),
    ]
