from copy import deepcopy
from dataclasses import dataclass

from rest_framework import status

from ..constants import (
    DEGRADED_SERVICE_MESSAGE,
    HEALTHY_SERVICE_STATUS,
    LEGACY_DUMMY_REVIEW_MARKERS,
    LEGACY_BOOK_METADATA_SOURCE,
    PROCESSING_NOTICE,
    PROFILE_BASIS_TO_THEME,
    RECOMMENDATION_ENGINE_VERSION,
    RECOMMENDATION_HISTORY_LIMIT,
    UNEXPECTED_ERROR_CODE,
    UNEXPECTED_ERROR_MESSAGE,
)
from ..exceptions import BookRecommendationUnavailable
from ..models import DailyBookRecommendation
from .profile_service import public_profile_basis


@dataclass(frozen=True)
class RecommendationResponse:
    payload: dict
    status_code: int = status.HTTP_200_OK


def changed_profile_themes(stored_basis, current_basis):
    stored_basis = stored_basis if isinstance(stored_basis, dict) else {}
    current_basis = current_basis if isinstance(current_basis, dict) else {}
    return [
        theme_id
        for basis_key, theme_id in PROFILE_BASIS_TO_THEME.items()
        if stored_basis.get(basis_key) != current_basis.get(basis_key)
    ]


def isbns_for_themes(isbn_map, theme_ids):
    allowed = set(theme_ids or [])
    return {
        theme_id: values
        for theme_id, values in (isbn_map or {}).items()
        if theme_id in allowed
    }


def recommendation_isbns(recommendation):
    isbns_by_theme = {}
    history = (
        recommendation.get("recommendation_history", {}).get("isbns", {})
        if isinstance(recommendation, dict) else {}
    )
    for theme_id, values in history.items():
        for value in values if isinstance(values, list) else []:
            isbn = str(value or "").strip()
            if isbn and isbn not in isbns_by_theme.setdefault(theme_id, []):
                isbns_by_theme[theme_id].append(isbn)
    books = recommendation.get("books", []) if isinstance(recommendation, dict) else []
    for book in books:
        if not isinstance(book, dict):
            continue
        theme_id = str(book.get("theme_id") or "").strip()
        isbn = str(book.get("isbn") or "").strip()
        if theme_id and isbn:
            isbns_by_theme.setdefault(theme_id, []).append(isbn)
    return isbns_by_theme


def merge_isbns_by_theme(*isbn_maps):
    merged = {}
    for isbn_map in isbn_maps:
        if not isinstance(isbn_map, dict):
            continue
        for theme_id, values in isbn_map.items():
            target = merged.setdefault(theme_id, [])
            iterable = values if isinstance(values, (list, tuple, set)) else []
            for value in iterable:
                isbn = str(value or "").strip()
                if isbn and isbn not in target:
                    target.append(isbn)
    return merged


def _engine_changed(daily_record):
    if not daily_record:
        return False
    stored_payload = daily_record.payload or {}
    stored_engine = stored_payload.get("recommendation_engine")
    stored_source = (stored_payload.get("source_disclosure") or {}).get("book_metadata")
    return bool(
        (stored_engine and stored_engine != RECOMMENDATION_ENGINE_VERSION)
        or (not stored_engine and stored_source == LEGACY_BOOK_METADATA_SOURCE)
    )


def payload_has_real_books(payload):
    """Reject empty book placeholders and reviews generated by the old dummy path."""
    if not isinstance(payload, dict):
        return False
    books = payload.get("books")
    if not isinstance(books, list) or not books:
        return False

    for book in books:
        if not isinstance(book, dict) or not str(book.get("title") or "").strip():
            return False
        review = str(
            (book.get("ai_curation") or {}).get("review")
            or book.get("review")
            or ""
        )
        if any(marker in review for marker in LEGACY_DUMMY_REVIEW_MARKERS):
            return False
    return True


def _recent_valid_previous_records(user, today):
    records = DailyBookRecommendation.objects.filter(
        user=user,
        recommendation_date__lt=today,
    ).order_by("-recommendation_date")
    valid = []
    for record in records.iterator():
        if payload_has_real_books(record.payload):
            valid.append(record)
            if len(valid) >= RECOMMENDATION_HISTORY_LIMIT:
                break
    return valid


def _latest_valid_previous_record(user, today):
    records = _recent_valid_previous_records(user, today)
    return records[0] if records else None


def _failure_response(exc):
    return RecommendationResponse(
        payload={"detail": str(exc), "code": exc.code, "retryable": True},
        status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
    )


def _unexpected_failure_response():
    return RecommendationResponse(
        payload={
            "detail": UNEXPECTED_ERROR_MESSAGE,
            "code": UNEXPECTED_ERROR_CODE,
            "retryable": True,
        },
        status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
    )


def build_recommendation_response(
    *,
    user,
    user_profile,
    today,
    recommendation_agent,
    force=False,
    force_theme=None,
):
    """Coordinate cache, persistence, regeneration, and degraded fallback."""
    daily_record = DailyBookRecommendation.objects.filter(
        user=user,
        recommendation_date=today,
    ).first()
    current_profile_basis = public_profile_basis(user_profile)
    changed_themes = (
        changed_profile_themes(daily_record.profile_basis, current_profile_basis)
        if daily_record
        else []
    )
    profile_changed = bool(changed_themes)
    engine_changed = _engine_changed(daily_record)
    daily_payload_valid = bool(daily_record) and payload_has_real_books(daily_record.payload)
    payload_invalid = bool(daily_record) and not daily_payload_valid

    recommendation = daily_record.payload if daily_payload_valid else None
    profile_basis = daily_record.profile_basis if daily_record else None
    content_date = daily_record.recommendation_date if daily_record else today
    is_cached = (
        daily_payload_valid
        and not force
        and not profile_changed
        and not engine_changed
    )
    is_stale = False
    service_status = deepcopy(HEALTHY_SERVICE_STATUS)

    if not is_cached:
        profile_basis = current_profile_basis
        previous_records = _recent_valid_previous_records(user, today)
        previous_record = previous_records[0] if previous_records else None
        previous_isbns = merge_isbns_by_theme(*(
            recommendation_isbns(record.payload) for record in previous_records
        ))
        if (force or engine_changed) and daily_payload_valid:
            previous_isbns = merge_isbns_by_theme(
                previous_isbns,
                recommendation_isbns(daily_record.payload),
            )
        elif profile_changed and daily_payload_valid:
            previous_isbns = merge_isbns_by_theme(
                previous_isbns,
                isbns_for_themes(
                    recommendation_isbns(daily_record.payload),
                    changed_themes,
                ),
            )

        automatic_force_theme = changed_themes[0] if len(changed_themes) == 1 else None
        try:
            recommendation = recommendation_agent.recommend(
                user_profile,
                force_theme=force_theme if force else automatic_force_theme,
                cached_data=(
                    daily_record.payload
                    if daily_payload_valid
                    else (previous_record.payload if previous_record else None)
                ),
                excluded_isbns=previous_isbns,
            )
            if not payload_has_real_books(recommendation):
                raise BookRecommendationUnavailable(
                    "완전한 실제 책 추천을 생성하지 못했습니다.",
                    code="BOOK_RECOMMENDATION_INVALID_PAYLOAD",
                )
        except BookRecommendationUnavailable as exc:
            fallback_record = daily_record if daily_payload_valid else previous_record
            if not fallback_record:
                return _failure_response(exc)
            recommendation = fallback_record.payload
            profile_basis = fallback_record.profile_basis
            content_date = fallback_record.recommendation_date
            is_cached = True
            is_stale = True
            service_status = {
                "state": "degraded",
                "retryable": True,
                "code": exc.code,
                "message": DEGRADED_SERVICE_MESSAGE,
            }
        except Exception as exc:
            print(f"[BookAgent] Unexpected recommendation failure: {exc}")
            fallback_record = daily_record if daily_payload_valid else previous_record
            if not fallback_record:
                return _unexpected_failure_response()
            recommendation = fallback_record.payload
            profile_basis = fallback_record.profile_basis
            content_date = fallback_record.recommendation_date
            is_cached = True
            is_stale = True
            service_status = {
                "state": "degraded",
                "retryable": True,
                "code": UNEXPECTED_ERROR_CODE,
                "message": DEGRADED_SERVICE_MESSAGE,
            }
        else:
            defaults = {"payload": recommendation, "profile_basis": profile_basis}
            if force or profile_changed or engine_changed or payload_invalid:
                daily_record, _ = DailyBookRecommendation.objects.update_or_create(
                    user=user,
                    recommendation_date=today,
                    defaults=defaults,
                )
            else:
                # The unique user/date constraint lets the first concurrent result win.
                daily_record, created = DailyBookRecommendation.objects.get_or_create(
                    user=user,
                    recommendation_date=today,
                    defaults=defaults,
                )
                if not created:
                    recommendation = daily_record.payload
                    profile_basis = daily_record.profile_basis
                    is_cached = True
            content_date = daily_record.recommendation_date

    return RecommendationResponse(
        payload={
            **recommendation,
            "is_cached": is_cached,
            "is_stale": is_stale,
            "service_status": service_status,
            "profile_basis": profile_basis or {},
            "content_date": content_date.isoformat(),
            "processing_notice": deepcopy(PROCESSING_NOTICE),
        }
    )
