# Generated by Django 4.2.30 on 2026-07-06 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MindReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('range_text', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('stress_causes', models.JSONField(default=list)),
                ('relief_causes', models.JSONField(default=list)),
                ('emotions', models.JSONField(default=list)),
                ('analysis', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('is_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mind_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mind_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
